/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DoAnVat.QuanLyDoAnVat;

import getAndSet.Menu;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import source.manageMenu;

/**
 *
 * @author HoaiAnh
 */
public class QuanLyMenu extends javax.swing.JPanel {

    /**
     * Creates new form QuanLyMayTinh
     */
    manageMenu mmn = new manageMenu();

    public void refresh() {
        dtm.setNumRows(0);
        try {
            List<Menu> listMenu = new ArrayList<>();
            listMenu = (List<Menu>) mmn.getListMenu();
            for (Menu mn : listMenu) {
                dtm.addRow(new Object[]{
                    mn.getMaMon(),
                    mn.getTenMon(),
                    mn.getGiaBan(),
                    mn.getLoaiMon()});
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    DefaultTableModel dtm = null;

    public QuanLyMenu() {
        initComponents();
        dtm = (DefaultTableModel) jTable1.getModel();
        refresh();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtMa_106 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTen_106 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtGia_106 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnAdd_106 = new javax.swing.JButton();
        btnChange_106 = new javax.swing.JButton();
        btnDel_106 = new javax.swing.JButton();
        btnRef_106 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtGia_107 = new javax.swing.JTextField();

        jLabel2.setText("jLabel2");

        setBackground(new java.awt.Color(204, 204, 0));
        setForeground(new java.awt.Color(255, 255, 255));
        setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("QUẢN LÝ MENU");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("MÃ MÓN:");

        txtMa_106.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("TÊN MÓN:");

        txtTen_106.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("GIÁ BÁN:");

        txtGia_106.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("PHÂN LOẠI:");

        btnAdd_106.setBackground(new java.awt.Color(255, 204, 204));
        btnAdd_106.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btnAdd_106.setText("THÊM");
        btnAdd_106.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdd_106ActionPerformed(evt);
            }
        });

        btnChange_106.setBackground(new java.awt.Color(255, 204, 204));
        btnChange_106.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btnChange_106.setText("SỬA");
        btnChange_106.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChange_106ActionPerformed(evt);
            }
        });

        btnDel_106.setBackground(new java.awt.Color(255, 204, 204));
        btnDel_106.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btnDel_106.setText("XÓA");
        btnDel_106.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDel_106ActionPerformed(evt);
            }
        });

        btnRef_106.setBackground(new java.awt.Color(255, 204, 204));
        btnRef_106.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btnRef_106.setText("LÀM MỚI");
        btnRef_106.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRef_106ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Món", "Tên Món", "Giá bán", "Phân loại"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        txtGia_107.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(btnAdd_106, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addComponent(btnChange_106)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDel_106, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(btnRef_106, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 591, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtMa_106)
                        .addComponent(txtTen_106)
                        .addComponent(txtGia_106, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtGia_107, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMa_106, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTen_106, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtGia_106, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGia_107, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd_106, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnChange_106, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDel_106, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRef_106, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdd_106ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdd_106ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnAdd_106ActionPerformed

    private void btnChange_106ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChange_106ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnChange_106ActionPerformed

    private void btnDel_106ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDel_106ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnDel_106ActionPerformed

    private void btnRef_106ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRef_106ActionPerformed
        // TODO add your handling code here:
        refresh();
    }//GEN-LAST:event_btnRef_106ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int row = jTable1.getSelectedRow();
        txtMa_106.setText(dtm.getValueAt(row, 0).toString());
        txtTen_106.setText(dtm.getValueAt(row, 1).toString());
        txtGia_106.setText(dtm.getValueAt(row, 2).toString());
        // combo box cbb_106
    }//GEN-LAST:event_jTable1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd_106;
    private javax.swing.JButton btnChange_106;
    private javax.swing.JButton btnDel_106;
    private javax.swing.JButton btnRef_106;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtGia_106;
    private javax.swing.JTextField txtGia_107;
    private javax.swing.JTextField txtMa_106;
    private javax.swing.JTextField txtTen_106;
    // End of variables declaration//GEN-END:variables
}
