/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package DoAnVat;

import DoAnVat.QuanLyDoAnVat.*;

/**
 *
 * @author HoaiAnh
 */
public class GiaoDienAdmin extends javax.swing.JPanel {

    /**
     * Creates new form giaoDienAdmin
     */
    public GiaoDienAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        pnMenu_106 = new javax.swing.JPanel();
        jbmenu = new javax.swing.JLabel();
        pnFood_106 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnNVien_106 = new javax.swing.JPanel();
        jbquanlynhanvien = new javax.swing.JLabel();
        pnThongKe_106 = new javax.swing.JPanel();
        jbthongke = new javax.swing.JLabel();
        logOut_106 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        jPanel4.setBackground(new java.awt.Color(204, 255, 204));

        pnMenu_106.setBackground(new java.awt.Color(0, 204, 204));
        pnMenu_106.setForeground(new java.awt.Color(255, 255, 255));

        jbmenu.setBackground(new java.awt.Color(0, 153, 102));
        jbmenu.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jbmenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jbmenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DoAnVat/icon/menu.png"))); // NOI18N
        jbmenu.setText("QUẢN LÝ MENU");

        javax.swing.GroupLayout pnMenu_106Layout = new javax.swing.GroupLayout(pnMenu_106);
        pnMenu_106.setLayout(pnMenu_106Layout);
        pnMenu_106Layout.setHorizontalGroup(
            pnMenu_106Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMenu_106Layout.createSequentialGroup()
                .addComponent(jbmenu, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnMenu_106Layout.setVerticalGroup(
            pnMenu_106Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jbmenu, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
        );

        pnFood_106.setBackground(new java.awt.Color(0, 204, 204));
        pnFood_106.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jLabel1.setBackground(new java.awt.Color(0, 153, 102));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel1.setText("BÁN ĐỒ ĂN VẶT");

        javax.swing.GroupLayout pnFood_106Layout = new javax.swing.GroupLayout(pnFood_106);
        pnFood_106.setLayout(pnFood_106Layout);
        pnFood_106Layout.setHorizontalGroup(
            pnFood_106Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnFood_106Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(36, 36, 36))
        );
        pnFood_106Layout.setVerticalGroup(
            pnFood_106Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnFood_106Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnNVien_106.setBackground(new java.awt.Color(0, 204, 204));

        jbquanlynhanvien.setBackground(new java.awt.Color(0, 204, 204));
        jbquanlynhanvien.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jbquanlynhanvien.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jbquanlynhanvien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DoAnVat/icon/icNV1.png"))); // NOI18N
        jbquanlynhanvien.setText("QUẢN LÝ NHÂN VIÊN");

        javax.swing.GroupLayout pnNVien_106Layout = new javax.swing.GroupLayout(pnNVien_106);
        pnNVien_106.setLayout(pnNVien_106Layout);
        pnNVien_106Layout.setHorizontalGroup(
            pnNVien_106Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnNVien_106Layout.createSequentialGroup()
                .addComponent(jbquanlynhanvien)
                .addGap(0, 11, Short.MAX_VALUE))
        );
        pnNVien_106Layout.setVerticalGroup(
            pnNVien_106Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jbquanlynhanvien, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
        );

        pnThongKe_106.setBackground(new java.awt.Color(0, 204, 204));

        jbthongke.setBackground(new java.awt.Color(0, 204, 204));
        jbthongke.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jbthongke.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jbthongke.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DoAnVat/icon/thke.jpg"))); // NOI18N
        jbthongke.setText("THỐNG KÊ");

        javax.swing.GroupLayout pnThongKe_106Layout = new javax.swing.GroupLayout(pnThongKe_106);
        pnThongKe_106.setLayout(pnThongKe_106Layout);
        pnThongKe_106Layout.setHorizontalGroup(
            pnThongKe_106Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnThongKe_106Layout.createSequentialGroup()
                .addComponent(jbthongke, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnThongKe_106Layout.setVerticalGroup(
            pnThongKe_106Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jbthongke, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        logOut_106.setBackground(new java.awt.Color(0, 204, 102));
        logOut_106.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        logOut_106.setText("ĐĂNG XUẤT");
        logOut_106.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        logOut_106.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOut_106ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnThongKe_106, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnFood_106, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnNVien_106, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnMenu_106, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logOut_106, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(pnFood_106, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(pnNVien_106, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(pnMenu_106, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(pnThongKe_106, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logOut_106, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        add(jPanel1, java.awt.BorderLayout.LINE_START);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 515, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 531, Short.MAX_VALUE)
        );

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void logOut_106ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOut_106ActionPerformed
        // TODO add your handling code here:
        /*this.setVisible(false);
        DangNhapMenu dkmt = new DangNhapMenu();
        dkmt.setVisible(true);*/
    }//GEN-LAST:event_logOut_106ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel jbmenu;
    private javax.swing.JLabel jbquanlynhanvien;
    private javax.swing.JLabel jbthongke;
    private javax.swing.JButton logOut_106;
    private javax.swing.JPanel pnFood_106;
    private javax.swing.JPanel pnMenu_106;
    private javax.swing.JPanel pnNVien_106;
    private javax.swing.JPanel pnThongKe_106;
    // End of variables declaration//GEN-END:variables
}
