/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GDAdmin;

import Controller.controllerGD;
import Controller.danhmuc;
import dangkydangnhap.DangNhapMenu;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author lynn
 */
public class GiaoDienAdmin extends javax.swing.JFrame {

    /**
     * Creates new form GDADMIN
     */
    public GiaoDienAdmin() {
        initComponents();
        controllerGD cgd = new controllerGD(jview);
        cgd.setView();
        List<danhmuc> listItem = new ArrayList<>();
        listItem.add(new danhmuc("NhanVien", pnNVien_106, jbquanlynhanvien));
        listItem.add(new danhmuc("Menu", pnMenu_106, jbmenu));
        listItem.add(new danhmuc("ThongKe", pnThongKe_106, jbthongke));
        cgd.setEvent(listItem);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        pnMenu_106 = new javax.swing.JPanel();
        jbmenu = new javax.swing.JLabel();
        pnFood_106 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnNVien_106 = new javax.swing.JPanel();
        jbquanlynhanvien = new javax.swing.JLabel();
        pnThongKe_106 = new javax.swing.JPanel();
        jbthongke = new javax.swing.JLabel();
        logOut_106 = new javax.swing.JButton();
        jview = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(204, 255, 204));

        pnMenu_106.setBackground(new java.awt.Color(0, 204, 204));
        pnMenu_106.setForeground(new java.awt.Color(255, 255, 255));

        jbmenu.setBackground(new java.awt.Color(0, 153, 102));
        jbmenu.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jbmenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jbmenu.setText("QUẢN LÝ MENU");

        javax.swing.GroupLayout pnMenu_106Layout = new javax.swing.GroupLayout(pnMenu_106);
        pnMenu_106.setLayout(pnMenu_106Layout);
        pnMenu_106Layout.setHorizontalGroup(
            pnMenu_106Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMenu_106Layout.createSequentialGroup()
                .addComponent(jbmenu, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnMenu_106Layout.setVerticalGroup(
            pnMenu_106Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jbmenu, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
        );

        pnFood_106.setBackground(new java.awt.Color(238, 34, 20));
        pnFood_106.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jLabel1.setBackground(new java.awt.Color(250, 255, 0));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(239, 255, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BÁN ĐỒ ĂN VẶT");

        javax.swing.GroupLayout pnFood_106Layout = new javax.swing.GroupLayout(pnFood_106);
        pnFood_106.setLayout(pnFood_106Layout);
        pnFood_106Layout.setHorizontalGroup(
            pnFood_106Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnFood_106Layout.setVerticalGroup(
            pnFood_106Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
        );

        pnNVien_106.setBackground(new java.awt.Color(0, 204, 204));

        jbquanlynhanvien.setBackground(new java.awt.Color(0, 204, 204));
        jbquanlynhanvien.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jbquanlynhanvien.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jbquanlynhanvien.setText("QUẢN LÝ NHÂN VIÊN");

        javax.swing.GroupLayout pnNVien_106Layout = new javax.swing.GroupLayout(pnNVien_106);
        pnNVien_106.setLayout(pnNVien_106Layout);
        pnNVien_106Layout.setHorizontalGroup(
            pnNVien_106Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jbquanlynhanvien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnNVien_106Layout.setVerticalGroup(
            pnNVien_106Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jbquanlynhanvien, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
        );

        pnThongKe_106.setBackground(new java.awt.Color(0, 204, 204));

        jbthongke.setBackground(new java.awt.Color(0, 204, 204));
        jbthongke.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jbthongke.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jbthongke.setText("THỐNG KÊ");

        javax.swing.GroupLayout pnThongKe_106Layout = new javax.swing.GroupLayout(pnThongKe_106);
        pnThongKe_106.setLayout(pnThongKe_106Layout);
        pnThongKe_106Layout.setHorizontalGroup(
            pnThongKe_106Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jbthongke, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnThongKe_106Layout.setVerticalGroup(
            pnThongKe_106Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jbthongke, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        logOut_106.setBackground(new java.awt.Color(0, 204, 102));
        logOut_106.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        logOut_106.setText("ĐĂNG XUẤT");
        logOut_106.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        logOut_106.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOut_106ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnThongKe_106, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnFood_106, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnNVien_106, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnMenu_106, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logOut_106, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(pnFood_106, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(pnNVien_106, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(pnMenu_106, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(pnThongKe_106, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addComponent(logOut_106, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jviewLayout = new javax.swing.GroupLayout(jview);
        jview.setLayout(jviewLayout);
        jviewLayout.setHorizontalGroup(
            jviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
        );
        jviewLayout.setVerticalGroup(
            jviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jview, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jview, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logOut_106ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOut_106ActionPerformed
        DangNhapMenu dnm = new DangNhapMenu();
        dnm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_logOut_106ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GiaoDienAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GiaoDienAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GiaoDienAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GiaoDienAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GiaoDienAdmin frame = new GiaoDienAdmin();
                frame.setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel jbmenu;
    private javax.swing.JLabel jbquanlynhanvien;
    private javax.swing.JLabel jbthongke;
    private javax.swing.JPanel jview;
    private javax.swing.JButton logOut_106;
    private javax.swing.JPanel pnFood_106;
    private javax.swing.JPanel pnMenu_106;
    private javax.swing.JPanel pnNVien_106;
    private javax.swing.JPanel pnThongKe_106;
    // End of variables declaration//GEN-END:variables
}
