/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GDAdmin;

import Controller.DK;
import GetAndSet.Menu;
import static java.time.zone.ZoneRulesProvider.refresh;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HoaiAnh
 */
public class GiaoDienMenu extends javax.swing.JPanel {

    /**
     * Creates new form GiaoDienMenu
     */
    int selectedIndex;
    DK qlService;
    DefaultTableModel defaultTableModel;
    private List<Menu> ql;
    private DefaultTableModel model;
    Menu menu;
    DK menudao;
    public GiaoDienMenu() {
        initComponents();
        this.setLocationRelativeTo(null);
        model = (DefaultTableModel)jTable1.getModel();
        showTable();
        menu = new Menu();
        menudao = new DK();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnBack_106 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnExit_106 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtMa_108 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtMa_107 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtMa_106 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtMa_109 = new javax.swing.JTextField();
        btnAdd_106 = new javax.swing.JButton();
        btnChange_106 = new javax.swing.JButton();
        btnDel_106 = new javax.swing.JButton();
        btnRef_106 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));

        btnBack_106.setBackground(new java.awt.Color(255, 255, 255));
        btnBack_106.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btnBack_106.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DoAnVat/back.png"))); // NOI18N
        btnBack_106.setText("Quay lại");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("QUẢN LÝ MENU");

        btnExit_106.setBackground(new java.awt.Color(255, 255, 255));
        btnExit_106.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btnExit_106.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DoAnVat/thoat.jpg"))); // NOI18N
        btnExit_106.setText("Thoát");

        jPanel2.setBackground(new java.awt.Color(153, 255, 153));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("MÃ MÓN:");

        txtMa_108.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("TÊN MÓN:");

        txtMa_107.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("GIÁ BÁN:");

        txtMa_106.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("PHÂN LOẠI:");

        txtMa_109.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        btnAdd_106.setBackground(new java.awt.Color(255, 204, 204));
        btnAdd_106.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btnAdd_106.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DoAnVat/add.png"))); // NOI18N
        btnAdd_106.setText("THÊM");
        btnAdd_106.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdd_106ActionPerformed(evt);
            }
        });

        btnChange_106.setBackground(new java.awt.Color(255, 204, 204));
        btnChange_106.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btnChange_106.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DoAnVat/edit1.png"))); // NOI18N
        btnChange_106.setText("SỬA");
        btnChange_106.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChange_106ActionPerformed(evt);
            }
        });

        btnDel_106.setBackground(new java.awt.Color(255, 204, 204));
        btnDel_106.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btnDel_106.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DoAnVat/xoa.png"))); // NOI18N
        btnDel_106.setText("XÓA");
        btnDel_106.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDel_106ActionPerformed(evt);
            }
        });

        btnRef_106.setBackground(new java.awt.Color(255, 204, 204));
        btnRef_106.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btnRef_106.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DoAnVat/lm.png"))); // NOI18N
        btnRef_106.setText("LÀM MỚI");
        btnRef_106.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRef_106ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Món", "Tên Món", "Giá bán", "Phân loại"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtMa_109, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtMa_106, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(299, 299, 299)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))
                                .addGap(40, 40, 40)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtMa_107, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMa_108, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(btnAdd_106)
                        .addGap(60, 60, 60)
                        .addComponent(btnChange_106)
                        .addGap(59, 59, 59)
                        .addComponent(btnDel_106, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(btnRef_106)))
                .addContainerGap(75, Short.MAX_VALUE))
            .addComponent(jSeparator1)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMa_108, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMa_107, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMa_106, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMa_109, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnChange_106, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdd_106, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDel_106, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRef_106, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(btnBack_106)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExit_106)
                .addGap(41, 41, 41))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 14, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(242, 242, 242))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExit_106)
                    .addComponent(btnBack_106))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        add(jPanel1, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdd_106ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdd_106ActionPerformed
        GiaoDienMenu ql1 = new GiaoDienMenu();
        menu.setMaDoAn(txtMa_108.getText());
        menu.setTenDoAn(txtMa_107.getText());
        menu.setLoaiDoAn(txtMa_106.getText());
        menu.setGiaThanh(txtMa_109.getText());
        menudao.addMenu(menu);
        ql1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAdd_106ActionPerformed

    private void btnChange_106ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChange_106ActionPerformed
        Menu mn = new Menu(txtMa_108.getText(), txtMa_107.getText(), txtMa_106.getText(), txtMa_109.getText());
        menudao.editMenu(mn);
        refresh();
    }//GEN-LAST:event_btnChange_106ActionPerformed

    private void btnDel_106ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDel_106ActionPerformed
        selectedIndex = jTable1.getSelectedRow();
        Menu qltv = ql.get(selectedIndex);
        JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xóa không?");
        new DK().deleteMenu(qltv.getMaDoAn());
        showTable();
    }//GEN-LAST:event_btnDel_106ActionPerformed

    private void btnRef_106ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRef_106ActionPerformed
        // TODO add your handling code here:
        //refresh();
    }//GEN-LAST:event_btnRef_106ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd_106;
    private javax.swing.JButton btnBack_106;
    private javax.swing.JButton btnChange_106;
    private javax.swing.JButton btnDel_106;
    private javax.swing.JButton btnExit_106;
    private javax.swing.JButton btnRef_106;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtMa_106;
    private javax.swing.JTextField txtMa_107;
    private javax.swing.JTextField txtMa_108;
    private javax.swing.JTextField txtMa_109;
    // End of variables declaration//GEN-END:variables

    private void setLocationRelativeTo(Object object) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void showTable() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void dispose() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
